# Generated by Django 4.1.6 on 2023-02-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_src',
            field=models.FileField(null=True, upload_to='covers/', verbose_name='Обладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_src',
            field=models.FileField(upload_to='books/', verbose_name='Книга'),
        ),
    ]
