# Generated by Django 4.1.6 on 2023-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_cover_src_alter_book_book_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_rendered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_src',
            field=models.FileField(upload_to='books/%S/', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_src',
            field=models.FileField(upload_to='covers/', verbose_name='Обладинка'),
        ),
    ]
