# Generated by Django 4.1.6 on 2023-03-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_description_remove_book_is_rendered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_tags',
            field=models.ManyToManyField(default=[], to='app.category', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_src',
            field=models.FileField(null=True, upload_to='covers/', verbose_name='Обладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
    ]
