# Generated by Django 4.1.6 on 2023-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_book_book_tags_alter_book_cover_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
    ]
